export const actionTypes = {
    SET_ACTIVE_USER_ID : "SET_ACTIVE_USER_ID",
    SET_TYPING_VALUE: "SET_TYPING_VALUE",
    SEND_MESSAGE: "SEND_MESSAGE",
    EDIT_MESSAGE: "EDIT_MESSAGE",
    UPDATE_MESSAGE: "UPDATE_MESSAGE"
}